# tests/hooks/guard-taboos/guests.sh — stopping or deleting a guest:
# the ask tier. Sourced by tests/hooks/guard-taboos.sh, in its
# order, into the one shell every part shares; never run on its own.
# shellcheck shell=sh

# --- a guest stopped or deleted -------------------------------
# Asked where a prompt can reach a human; denied without a
# permission mode, which counts as no prompt, and in the modes that
# show none.
check deny 'pct stop 105'
check_mode ask default 'pct stop 105'
check deny 'pct shutdown 105'
check_mode ask default 'pct shutdown 105'
check deny 'ssh root@pve1 "pct stop 105"'
check_mode ask default 'ssh root@pve1 "pct stop 105"'
check deny 'incus stop web'
check_mode ask default 'incus stop web'
check deny 'incus --project prod stop web'
check_mode ask default 'incus --project prod stop web'
check deny 'incus stop --all'
check_mode ask default 'incus stop --all'
check deny 'incus -q stop web'
check_mode ask default 'incus -q stop web'
check deny 'incus --project=prod stop web'
check_mode ask default 'incus --project=prod stop web'
check deny 'lxc --force-local stop web'
check_mode ask default 'lxc --force-local stop web'
check deny 'qm stop 100'
check_mode ask default 'qm stop 100'
check deny 'qm shutdown 100 --timeout 60'
check_mode ask default 'qm shutdown 100 --timeout 60'
check deny 'pct destroy 105'
check_mode ask default 'pct destroy 105'
check deny 'qm destroy 100 --purge'
check_mode ask default 'qm destroy 100 --purge'
check deny 'incus delete --force web'
check_mode ask default 'incus delete --force web'
check deny 'incus --project prod delete web'
check_mode ask default 'incus --project prod delete web'
check deny 'lxc delete -f web'
check_mode ask default 'lxc delete -f web'
check deny 'virsh undefine web --remove-all-storage'
check_mode ask default 'virsh undefine web --remove-all-storage'
check deny 'virsh -c qemu:///system undefine web'
check_mode ask default 'virsh -c qemu:///system undefine web'
check deny 'lxc-destroy -n web'
check_mode ask default 'lxc-destroy -n web'
check deny 'ssh root@pve1 "qm stop 100 --skiplock"'
check_mode ask default 'ssh root@pve1 "qm stop 100 --skiplock"'
check deny 'virsh destroy web'
check_mode ask default 'virsh destroy web'
check deny 'virsh destroy web --graceful'
check_mode ask default 'virsh destroy web --graceful'
check deny 'virsh shutdown web'
check_mode ask default 'virsh shutdown web'
check deny 'virsh -c qemu:///system destroy web'
check_mode ask default 'virsh -c qemu:///system destroy web'
check deny 'virsh -c qemu:///system shutdown web'
check_mode ask default 'virsh -c qemu:///system shutdown web'
check deny 'virsh --connect qemu:///system destroy web'
check_mode ask default 'virsh --connect qemu:///system destroy web'
check deny 'lxc stop web --force'
check_mode ask default 'lxc stop web --force'
check deny 'lxc-stop -n web'
check_mode ask default 'lxc-stop -n web'
check deny 'lxc-stop -n web -k'
check_mode ask default 'lxc-stop -n web -k'
check deny 'xe vm-shutdown uuid=abc123'
check_mode ask default 'xe vm-shutdown uuid=abc123'
check deny 'xe vm-shutdown uuid=abc123 force=true'
check_mode ask default 'xe vm-shutdown uuid=abc123 force=true'
check deny 'xe vm-uninstall uuid=abc123 --force'
check_mode ask default 'xe vm-uninstall uuid=abc123 --force'
check deny 'xe vm-destroy uuid=abc123'
check_mode ask default 'xe vm-destroy uuid=abc123'
check deny 'xe -s pool1 -u root vm-shutdown uuid=abc123'
check_mode ask default 'xe -s pool1 -u root vm-shutdown uuid=abc123'
check deny 'ssh root@xen1 "xe vm-uninstall uuid=abc123"'
check_mode ask default 'ssh root@xen1 "xe vm-uninstall uuid=abc123"'
check_mode deny default 'xe vm-shutdown uuid=abc123; shutdown -h now'
check deny 'midclt call vm.stop 1'
check_mode ask default 'midclt call vm.stop 1'
# vm.poweroff spells the word the rule above denies in every
# mode. Stricter than the ask tier, and left that way.
check deny 'midclt call vm.poweroff 1'
check_mode deny default 'midclt call vm.poweroff 1'
check deny 'midclt call vm.delete 1'
check_mode ask default 'midclt call vm.delete 1'
check deny 'midclt call virt.instance.stop web'
check_mode ask default 'midclt call virt.instance.stop web'
check deny 'midclt call virt.instance.delete web'
check_mode ask default 'midclt call virt.instance.delete web'
check deny 'ssh root@nas1 "midclt call vm.delete 1"'
check_mode ask default 'ssh root@nas1 "midclt call vm.delete 1"'
check dev-deny 'midclt call vm.delete 1'
check deny 'pct stop 105 && pct destroy 105'
check_mode ask default 'pct stop 105 && pct destroy 105'
check dev-deny 'pct stop 105'
check dev-deny 'lxc-destroy -n web'
check dev-deny 'xe vm-destroy uuid=abc123'
check dev-deny 'xe -s pool1 vm-destroy uuid=abc123'
check dev-deny 'incus delete --force web'
check dev-deny 'virsh undefine web'
check dev-deny 'qm destroy 100'
check dev-deny 'ssh root@nas1.example.com "zpool destroy tank"'
check dev-deny 'ssh root@nas1.example.com "lvextend -L +1G vg0/root"'
# FreeBSD jails, by Bastille, iocage, jail(8) and the rc scripts
# that start them: the same ask, and the same deny without a
# human.
check deny 'bastille stop web'
check_mode ask default 'bastille stop web'
check deny 'bastille destroy web'
check_mode ask default 'bastille destroy web'
check deny 'bastille destroy -f web'
check_mode ask default 'bastille destroy -f web'
check deny 'iocage stop web'
check_mode ask default 'iocage stop web'
check deny 'iocage stop ALL'
check_mode ask default 'iocage stop ALL'
check deny 'iocage destroy -f web'
check_mode ask default 'iocage destroy -f web'
check deny 'jail -r web'
check_mode ask default 'jail -r web'
check deny 'jail -R web'
check_mode ask default 'jail -R web'
check deny 'jail -rc web'
check_mode ask default 'jail -rc web'
check deny 'jail -f /etc/jail.conf -r web'
check_mode ask default 'jail -f /etc/jail.conf -r web'
check deny '/usr/sbin/jail -r web'
check_mode ask default '/usr/sbin/jail -r web'
check deny 'service jail stop'
check_mode ask default 'service jail stop'
check deny 'service jail stop web'
check_mode ask default 'service jail stop web'
check deny 'service jail onestop web'
check_mode ask default 'service jail onestop web'
check deny 'service bastille stop'
check_mode ask default 'service bastille stop'
check deny 'service iocage stop'
check_mode ask default 'service iocage stop'
check deny '/etc/rc.d/jail stop web'
check_mode ask default '/etc/rc.d/jail stop web'
check deny 'ssh root@bsd1 "bastille stop web"'
check_mode ask default 'ssh root@bsd1 "bastille stop web"'
check deny 'ssh root@bsd1 "iocage destroy -f web"'
check_mode ask default 'ssh root@bsd1 "iocage destroy -f web"'
check dev-deny 'bastille stop web'
check dev-deny 'iocage destroy -f web'
check dev-deny 'jail -r web'
check dev-deny 'service jail stop web'
check_mode deny bypassPermissions 'bastille destroy web'
check_mode ask auto 'iocage stop web'
# A jail restarts through a stop, so it asks the same way.
check deny 'bastille restart web'
check_mode ask default 'bastille restart web'
check deny 'iocage restart web'
check_mode ask default 'iocage restart web'
check deny 'jail -rc web'
check_mode ask default 'jail -rc web'
check deny 'service jail restart'
check_mode ask default 'service jail restart'
check deny 'service jail restart web'
check_mode ask default 'service jail restart web'
check deny 'service jail onerestart web'
check_mode ask default 'service jail onerestart web'
check deny 'service jail forcerestart web'
check_mode ask default 'service jail forcerestart web'
check deny 'service bastille restart'
check_mode ask default 'service bastille restart'
check deny 'service iocage restart'
check_mode ask default 'service iocage restart'
check deny '/etc/rc.d/jail restart web'
check_mode ask default '/etc/rc.d/jail restart web'
check deny '/usr/local/etc/rc.d/bastille restart'
check_mode ask default '/usr/local/etc/rc.d/bastille restart'
check deny 'ssh root@bsd1 "service jail restart web"'
check_mode ask default 'ssh root@bsd1 "service jail restart web"'
check dev-deny 'bastille restart web'
check dev-deny 'service jail restart web'
check_mode deny bypassPermissions 'iocage restart web'
check_mode ask auto 'service jail onerestart web'
check pass 'bastille restart --help'
check pass 'service jail status web'
for m in acceptEdits plan auto; do
  check_mode ask "$m" 'pct stop 105'
done
for m in bypassPermissions dontAsk bogus; do
  check_mode deny "$m" 'pct stop 105'
done
# A host taboo in the same command still wins over the ask, and a
# guest's shutdown verb does not lend the host's its exemption.
check_mode deny default 'pct stop 105; mkfs.ext4 /dev/sda1'
check_mode deny default 'qm destroy 100 && reboot -f; halt'
check_mode deny default 'pct shutdown 105; shutdown -h now'
check_mode deny default 'ssh root@h "qm shutdown 100 && shutdown now"'
check_mode deny default 'pct exec 105 -- shutdown -h now'
