#!/usr/bin/env python3
"""Build and check a repository's decision records.

Copy this into the repository as `scripts/decisions.py` and put `--check` into
the check chain that CI runs. It reads the records under `docs/adr/` and
the derived rules that cite them, writes the index, and reports every way the
two can disagree.

    python3 scripts/decisions.py --write    # regenerate the index
    python3 scripts/decisions.py --check    # for CI; exits 1 on any problem

Standard library only, so it runs wherever Python 3 does and adds no dependency
to a repository that only wants the check.
"""

import argparse
import os
import posixpath
import re
import sys
from pathlib import Path, PurePosixPath

STATUSES = ("proposed", "accepted", "rejected", "superseded")

# The section vocabulary comes from the two templates beside this script. A
# heading outside it is reported rather than ignored: an unknown section is not
# covered by any budget below, which would make renaming `## Context` the way
# around the whole check.
SHORT_SECTIONS = ("Context", "Decision", "Consequences")
FULL_SECTIONS = (
    "Context",
    "Decision drivers",
    "Considered options",
    "Decision",
    "Consequences",
    "Confirmation",
)
FULL_ONLY = ("Decision drivers", "Considered options", "Confirmation")

# Word budgets. An agent drafts most of these, and an agent pads: it restates
# the code in Context and turns Consequences into an essay. So the sections
# where padding happens are capped flat, and the parts where complexity is
# genuine -- one paragraph per option considered, one line per driver -- are
# capped per item and scale with the decision. The whole record is capped too,
# or the padding just moves into a section nobody named a limit for.
SHORT_LIMITS = {"Context": 80, "Decision": 30, "Consequences": 80}
FULL_LIMITS = {"Context": 120, "Decision": 60, "Consequences": 120, "Confirmation": 60}
PER_OPTION = 120
PER_DRIVER = 25
MAX_DRIVERS = 5
TITLE_WORDS = 10
SHORT_TOTAL = 250
FULL_BASE, FULL_PER_OPTION = 400, 150

# A record is named by the day it was written. Sequential numbers would be
# shorter to say, but two worktrees hand out the same one and only find out at
# the merge, and Workoho repositories expect agents working in parallel.
ID_RE = re.compile(r"^\d{8}-[a-z0-9]+(-[a-z0-9]+)*$")

KEY_RE = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*)\s*:")
# Both fence characters, and runs longer than three of them. A rule's only
# `Source:` line sitting inside a tilde-fenced example would otherwise count as
# its backlink.
FENCE_OPEN_RE = re.compile(r"^(`{3,}|~{3,})")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
LINK_RE = re.compile(r"\[([^\]]*)\]\([^)]*\)")
INLINE_CODE_RE = re.compile(r"`[^`]*`")
BULLET_RE = re.compile(r"^\s*[-*]\s+(.*)$")
SOURCE_RE = re.compile(r"(?m)^Source:\s*(\S+)\s*$")

# The path this was run from is deliberately not in the generated header: the
# header is compared byte for byte, and this script lives at `scripts/` in most
# repositories and inside the skill in the one that defines the practice. A
# path there would make the same index read as out of date depending on which
# copy regenerated it.
GENERATED = "<!-- Generated by decisions.py --write. Do not edit by hand. -->"

# Where this skill keeps the templates it ships. Only this path is skipped, so a
# repository with its own `assets/templates` source tree keeps its rules.
SHIPPED_TEMPLATES = "skills/decision-records/assets/templates"

# Directories inside the repository that never hold a record or a rule. Matched
# against the path relative to the repository root: against the absolute path, a
# checkout living under any directory named `build` or `target` would skip every
# candidate and pass silently.
# Only names that are generated output by convention. A bare `site`, `public`
# or `themes` is a real source tree in plenty of repositories, and pruning one
# hides every rule under it while the check still passes.
SKIP_DIRS = {
    ".git",
    "node_modules",
    "dist",
    "build",
    ".venv",
    "__pycache__",
    "_site",
    "_build",
    ".docusaurus",
    ".cache",
    ".next",
    "vendor",
    "target",
}

problems = []


def fail(where, message):
    problems.append(f"{where}: {message}")


def plural(count):
    return "" if count == 1 else "s"


def rerun_command(repo):
    """The command a reader should type to fix a stale index.

    Built from the actual invocation, arguments included: with `--repo` or
    `--root` in play, a bare command would regenerate a different repository's
    index than the one just reported on.
    """
    called = Path(sys.argv[0])
    try:
        name = called.resolve().relative_to(repo).as_posix()
    except ValueError:
        name = called.as_posix()
    rest = [argument for argument in sys.argv[1:] if argument != "--check"]
    return " ".join(["python3", name, "--write"] + rest)


# --- the YAML subset these files use ---------------------------------------
#
# Hand-rolled on purpose. PyYAML is not in the standard library, and a
# repository should not take a dependency in order to run one check.


def strip_comment(raw):
    """Drop a trailing `# ...` comment, leaving `#` inside a value alone.

    YAML wants whitespace before the `#` that opens a comment, which is what
    separates `rule:   # a path or a list` from a URL ending in an anchor. The
    templates ship with such comments, so a parser that missed this would read
    the comment as the value.
    """
    quote = ""
    for index, char in enumerate(raw):
        if quote:
            if char == quote:
                quote = ""
        elif char in "\"'":
            quote = char
        elif char == "#" and (index == 0 or raw[index - 1] in " \t"):
            return raw[:index]
    return raw


def split_items(value):
    """Split an inline list on the commas that separate items.

    A plain `split(",")` tears `"**/*.{md,txt}"` into two malformed patterns,
    and the glob-scope check then cannot see what the rule really covers —
    brace expansion is documented syntax and the skill's own template uses it.
    """
    items, current, quote, depth = [], [], "", 0
    for char in value:
        if quote:
            if char == quote:
                quote = ""
        elif char in "\"'":
            quote = char
        elif char == "{":
            depth += 1
        elif char == "}":
            depth = max(0, depth - 1)
        elif char == "," and depth == 0:
            items.append("".join(current))
            current = []
            continue
        current.append(char)
    items.append("".join(current))
    return [item for item in items if item.strip()]


def unquote(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1]
    return value


def split_frontmatter(text):
    """(lines, error). The two ways a block is unusable are told apart: an
    author whose closing --- is missing must not be sent to the first line."""
    lines = text.split("\n")
    if not lines or lines[0].rstrip() != "---":
        return None, "no frontmatter; the opening --- must be the first line"
    for index in range(1, len(lines)):
        if lines[index].rstrip() == "---":
            return lines[1:index], None
    return None, "the frontmatter is never closed with ---"


def entries(front, key):
    """Every value of a top-level key: inline scalar, inline list, or a block
    sequence at either indentation.

    A block sequence may sit at the key's own indentation -- `rule:` followed by
    an unindented `- path` is valid YAML. Reading only the indented form returns
    an empty list there and silently skips every check over the entries.
    """
    for index, line in enumerate(front):
        if line[:1] in (" ", "\t", "-"):
            continue
        match = KEY_RE.match(line)
        if not match or match.group(1) != key:
            continue
        value = strip_comment(line.split(":", 1)[1]).strip()
        if value.startswith("[") and value.endswith("]"):
            return [unquote(part) for part in split_items(value[1:-1])]
        if value:
            return [unquote(value)]
        items = []
        for follow in front[index + 1 :]:
            if not follow.strip() or follow.lstrip().startswith("#"):
                continue
            stripped = follow.strip()
            if not stripped.startswith("-"):
                break
            items.append(unquote(strip_comment(stripped[1:])))
        return items
    return []


def duplicate_keys(front):
    """Top-level keys given more than once, in the order they first appear."""
    seen, repeated = set(), []
    for line in front:
        if (
            not line.strip()
            or line[:1] in (" ", "\t", "-")
            or line.lstrip().startswith("#")
        ):
            continue
        match = KEY_RE.match(line)
        if not match:
            continue
        if match.group(1) in seen and match.group(1) not in repeated:
            repeated.append(match.group(1))
        seen.add(match.group(1))
    return repeated


def scalar(front, key):
    found = entries(front, key)
    return found[0] if found else ""


# --- the documents ---------------------------------------------------------


def read(path):
    return path.read_text(encoding="utf-8")


def strip_fences(text):
    """Drop fenced blocks, the way CommonMark actually delimits them.

    Written as a scanner rather than one regular expression after four rounds
    of review each finding the next axis a pattern had missed: indentation, the
    tilde character, runs longer than three, trailing text on the closer, and a
    closer longer than its opener. A closer must repeat the opener's character
    at least as many times and carry nothing but whitespace.
    """
    kept, fence = [], None
    for line in text.split("\n"):
        body = line.lstrip(" ")
        indented = len(line) - len(body)
        if fence is None:
            opener = FENCE_OPEN_RE.match(body)
            if opener and indented <= 3:
                fence = opener.group(1)
            else:
                kept.append(line)
        elif (
            indented <= 3
            and body.rstrip() == body.rstrip(" \t")
            and re.match(rf"^{fence[0]}{{{len(fence)},}}[ \t]*$", body)
        ):
            fence = None
    return "\n".join(kept)


def strip_frontmatter(text):
    """Remove the block `split_frontmatter` accepted, by the same rule.

    An exact split on "\\n---\\n" missed a closing delimiter with trailing
    spaces, which the parser accepts -- and the frontmatter then counted toward
    the word budget and its comments were read as headings.
    """
    lines = text.split("\n")
    if not lines or lines[0].rstrip() != "---":
        return text
    for index in range(1, len(lines)):
        if lines[index].rstrip() == "---":
            return "\n".join(lines[index + 1 :])
    return text


def rule_body(text):
    """The constraint itself, without frontmatter, backlink or whitespace.

    Two files can carry the same rule in the paired-file fallback, and what
    has to match between them is what the agent acts on -- not the `paths:`
    frontmatter, which only Claude Code reads.
    """
    return " ".join(SOURCE_RE.sub("", strip_fences(strip_frontmatter(text))).split())


class Record:
    def __init__(self, path, decisions, repo, text):
        self.path = path
        self.text = text
        self.relative = path.relative_to(decisions).as_posix()
        self.where = path.relative_to(repo).as_posix()
        front, self.frontmatter_error = split_frontmatter(text)
        front = front or []
        self.repeated_keys = duplicate_keys(front)
        self.id = scalar(front, "id")
        self.status = scalar(front, "status")
        self.supersedes = scalar(front, "supersedes")
        self.superseded_by = scalar(front, "superseded-by")
        self.waiting_on = scalar(front, "waiting-on")
        self.rules = entries(front, "rule")
        self.tags = entries(front, "tags")
        titles = [
            match.group(2)
            for match in (
                HEADING_RE.match(line)
                for line in strip_fences(strip_frontmatter(text)).splitlines()
            )
            if match and len(match.group(1)) == 1
        ]
        self.titles = titles
        self.title = titles[0] if titles else (self.id or path.stem)


class Rule:
    def __init__(self, path, repo, text, in_rules_dir):
        self.path = path
        self.where = path.relative_to(repo).as_posix()
        self.in_rules_dir = in_rules_dir
        self.text = text
        self.body = rule_body(text)
        front, _ = split_frontmatter(text)
        self.paths = entries(front or [], "paths")
        source = SOURCE_RE.search(strip_fences(text))
        self.source = source.group(1) if source else ""


def collect_records(decisions, repo):
    records = []
    for path in sorted(decisions.rglob("*.md")):
        if path.name != "README.md":
            records.append(Record(path, decisions, repo, read(path)))
    return records


def collect_rules(repo, decisions):
    """Every file that cites a record, plus everything under `.claude/rules/`.

    A rule is recognized by its `Source:` line rather than by where it sits, so
    a rule written into a directory's `AGENTS.md` is checked like one under
    `.claude/rules/`. Everything in `.claude/rules/` counts even without the
    line, because a rule missing its backlink is exactly what the check is for.

    What makes a `Source:` line a citation is that it points into the decisions
    directory. Any markdown file may carry one -- a rule in a `plugins/README.md`
    is a rule -- and the target is what tells a citation from a sentence that
    happens to start with the word. Without it, `Source: the Affinity document`
    in somebody's asset README becomes a rule that has to cite a record, and the
    check fails on a file nobody meant as one.

    The skipped directories are pruned during the walk rather than filtered
    afterwards: `node_modules` in a consuming repository is by far the most
    expensive thing here, and descending into it to throw the result away is
    pure waste.
    """
    rules_dir = repo / ".claude" / "rules"
    prefix = decisions.relative_to(repo).as_posix().rstrip("/") + "/"
    candidates = []
    for root, dirs, files in os.walk(repo):
        here = Path(root)
        dirs[:] = sorted(name for name in dirs if name not in SKIP_DIRS)
        if here.name == ".claude" and "worktrees" in dirs:
            # Other worktrees of the same repository: their records and rules
            # belong to their own branch, and walking them from here reports
            # another session's work as this one's.
            dirs.remove("worktrees")
        in_rules_dir = here == rules_dir or rules_dir in here.parents
        # This skill's own shipped templates are forms, not repository
        # content: the `Source:` line in one is the shape a rule fills in, and
        # the file it names is a placeholder. Named as the one path it is,
        # because `assets/templates` is a source directory somebody else has.
        if here.relative_to(repo).as_posix().endswith(SHIPPED_TEMPLATES):
            continue
        for name in sorted(files):
            if name.endswith(".md"):
                candidates.append((here / name, in_rules_dir))
    rules, seen = [], set()
    for path, in_rules_dir in candidates:
        # `ln -s AGENTS.md CLAUDE.md` is one rule wearing two names. Collected
        # twice it would have to be declared twice, and the documented fallback
        # could never satisfy the backlink check.
        if path.is_symlink():
            target = path.resolve()
            if target in seen:
                continue
        seen.add(path.resolve())
        try:
            text = read(path)
        except (OSError, UnicodeDecodeError):
            # A file this walk was never meant to read: a dangling symlink, or
            # markdown in another encoding somewhere in a vendored tree. It
            # cannot be a rule, and taking the whole check chain down over it
            # would be a failure about the wrong file.
            continue
        # Cheap gate before the line scanner: `strip_fences` only removes text,
        # so a file with no literal `Source:` cannot match after stripping.
        if "Source:" not in text and not in_rules_dir:
            continue
        rule = Rule(path, repo, text, in_rules_dir)
        # One of Hostwarden's two changes to this file: its `.claude/rules/`
        # holds conventions for changing the repository, most of them with no
        # record behind them, so a file there is a rule only when it cites
        # one, as everywhere else. docs/adr/20260924-cite-only-rules.md says
        # why.
        if rule.source.startswith(prefix):
            rules.append(rule)
    return rules


# --- counting --------------------------------------------------------------


def count_words(lines):
    """What a reader actually reads.

    Headings, frontmatter and fenced blocks are outside the budget: a heading
    is structure, and a quoted error message or a config snippet is evidence,
    not padding. A link counts as its text, inline code as one word.
    """
    body = "\n".join(line for line in lines if not HEADING_RE.match(line))
    body = LINK_RE.sub(r"\1", body)
    body = INLINE_CODE_RE.sub("x", body)
    return len(body.split())


def bullets(lines):
    """Each bullet with the lines it wraps onto.

    Markdown wraps a long bullet over continuation lines, indented or not --
    an unindented one is a lazy continuation and belongs to the bullet just the
    same. Reading only the line that starts with the dash puts most of a long
    driver outside its budget, which is how ordinary formatting would have
    defeated the check. A blank line ends a lazy continuation; an indented line
    continues the bullet even across one.
    """
    found, running = [], False
    for line in lines:
        match = BULLET_RE.match(line)
        if match:
            found.append([match.group(1)])
            running = True
        elif not line.strip():
            running = False
        elif found and (running or line[:1] in (" ", "\t")):
            found[-1].append(line.strip())
            running = True
    return [" ".join(parts) for parts in found]


def block_words(sections, index):
    """A section's own prose plus everything nested under it.

    A budget that counted only the lines directly under `## Context` would be
    escaped by moving the prose under a `### Details` — the heading costs
    nothing and the words stop being counted.
    """
    level = sections[index][0]
    total = count_words(sections[index][2])
    for following_level, _, lines in sections[index + 1 :]:
        if following_level <= level:
            break
        total += count_words(lines)
    return total


def outline(text):
    """(level, title, own lines) per heading, in order. Frontmatter and fenced
    blocks are removed first so a `#` inside either is not read as a heading."""
    text = strip_fences(strip_frontmatter(text))
    sections, current = [], None
    for line in text.splitlines():
        heading = HEADING_RE.match(line)
        if heading:
            current = [len(heading.group(1)), heading.group(2), []]
            sections.append(current)
        elif current is not None:
            current[2].append(line)
    return sections


def brace_end(pattern, start):
    """Index of the `}` closing the `{` at `start`, or -1. Braces nest."""
    depth = 0
    for index in range(start, len(pattern)):
        if pattern[index] == "{":
            depth += 1
        elif pattern[index] == "}":
            depth -= 1
            if depth == 0:
                return index
    return -1


def brace_alternatives(inner):
    """Split on the commas that separate alternatives, not on nested ones."""
    parts, current, depth = [], [], 0
    for char in inner:
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
        elif char == "," and depth == 0:
            parts.append("".join(current))
            current = []
            continue
        current.append(char)
    parts.append("".join(current))
    return parts


def glob_body(pattern):
    """A glob translated to a regular expression body.

    `**` crosses directory separators, `*` and `?` do not. `fnmatch` lets a
    single `*` swallow slashes, which would report every `*.md` rule as
    covering the records, and that distinction is the whole point of the check.

    A brace alternative is translated recursively rather than escaped:
    `docs/{decisions/**,other/**}` is documented syntax, and escaping the
    alternatives whole turned the wildcards inside them into literal text --
    which let exactly such a rule reach the records unreported.
    """
    out = []
    index = 0
    while index < len(pattern):
        char = pattern[index]
        if char == "*":
            if pattern[index : index + 3] == "**/":
                out.append("(?:.*/)?")
                index += 3
                continue
            if pattern[index : index + 2] == "**":
                out.append(".*")
                index += 2
                continue
            out.append("[^/]*")
        elif char == "?":
            out.append("[^/]")
        elif char == "{":
            end = brace_end(pattern, index)
            if end != -1:
                out.append(
                    "(?:{})".format(
                        "|".join(
                            glob_body(part)
                            for part in brace_alternatives(pattern[index + 1 : end])
                        )
                    )
                )
                index = end + 1
                continue
            out.append(re.escape(char))
        else:
            out.append(re.escape(char))
        index += 1
    return "".join(out)


def glob_to_regex(pattern):
    return re.compile("(?s)\\A" + glob_body(pattern) + "\\Z")


def normalize(repo, path):
    """A repository-relative path, normalized without following symlinks.

    `Path.resolve()` would collapse the documented `ln -s AGENTS.md CLAUDE.md`
    fallback onto its target, so a rule discovered as `CLAUDE.md` and declared
    as `CLAUDE.md` would compare unequal and the setup could never pass.

    `posixpath`, not `os.path`: every other path here is `as_posix()`, and on
    Windows `os.path.normpath` hands back backslashes that then match nothing.
    """
    del repo
    return posixpath.normpath(str(PurePosixPath(path)))


# --- the checks, one named pass each ---------------------------------------
#
# Named rather than run as one long procedure because the passes walk different
# collections: which one is being walked has to be answerable from a signature,
# not from indentation depth. The last time it was not, the glob-scope check
# ended up inside the record loop reading a leaked variable.


def check_identity(records):
    """Frontmatter, filename and status. Returns the records by id."""
    by_id = {}
    for record in records:
        if record.frontmatter_error:
            fail(record.where, record.frontmatter_error)
            continue
        stem = record.path.stem
        if not ID_RE.match(stem):
            fail(record.where, "the filename is not YYYYMMDD-slug.md")
        if not record.id:
            fail(record.where, "no id")
        elif record.id != stem:
            fail(record.where, f"id '{record.id}' does not match the filename '{stem}'")
        for key in record.repeated_keys:
            fail(
                record.where,
                f"'{key}' is given more than once; the first wins "
                "silently and the file says two things at once",
            )
        if record.status not in STATUSES:
            fail(
                record.where,
                "status '{}' is not one of {}".format(
                    record.status, ", ".join(STATUSES)
                ),
            )
        if record.status == "proposed" and not record.waiting_on:
            fail(
                record.where,
                "is still proposed and names no waiting-on. A "
                "record merges as proposed only when it is "
                "parked on something nameable; otherwise set it "
                "to accepted or rejected when the review lands",
            )
        if record.id and record.id in by_id:
            fail(
                record.where,
                f"id '{record.id}' is already used by {by_id[record.id].relative}",
            )
        elif record.id:
            by_id[record.id] = record
    return by_id


def check_supersede(records, by_id):
    """The two halves of a supersede, each against the other."""
    mirrors = (
        ("superseded_by", "supersedes", "superseded-by", "supersedes"),
        ("supersedes", "superseded_by", "supersedes", "superseded-by"),
    )
    for record in records:
        if record.superseded_by and record.status != "superseded":
            fail(
                record.where,
                f"names a superseded-by but its status is '{record.status}'",
            )
        if record.status == "superseded" and not record.superseded_by:
            fail(
                record.where,
                "is superseded but names no superseded-by; "
                "'does this still hold' has to be answerable "
                "from this file alone",
            )
        if record.superseded_by:
            other = by_id.get(record.superseded_by)
            if other is not None and other.status not in ("accepted", "superseded"):
                fail(
                    record.where,
                    f"superseded-by names '{record.superseded_by}', whose status is "
                    f"'{other.status}'. Only a decision that took effect can "
                    "be what replaced this one, or the index "
                    "takes this one out of force and puts "
                    "nothing in its place",
                )
        for field in ("superseded_by", "supersedes"):
            if getattr(record, field) == record.id and record.id:
                fail(
                    record.where,
                    "{} names this record itself; a decision "
                    "cannot replace itself".format(field.replace("_", "-")),
                )
        for own, mirror, own_name, mirror_name in mirrors:
            pointer = getattr(record, own)
            if not pointer:
                continue
            other = by_id.get(pointer)
            if other is None:
                fail(
                    record.where, f"{own_name} names '{pointer}', which is not a record"
                )
            elif getattr(other, mirror) != record.id:
                fail(
                    record.where,
                    f"{own_name} names '{pointer}', which does not name this "
                    f"record back in {mirror_name}",
                )


def check_supersede_chains(records, by_id):
    """No closed loop in the supersede chain.

    Every pair in a cycle mirrors the next one correctly, so the pairwise check
    cannot see it -- and the index would then claim a decision was replaced by
    something it replaced. Reported once, from the lowest id in the loop.
    """
    for record in records:
        if not record.id or record.superseded_by == record.id:
            continue
        seen, current = [record.id], record
        while current.superseded_by:
            following = by_id.get(current.superseded_by)
            if following is None:
                break
            if following.id in seen:
                loop = seen[seen.index(following.id) :]
                if record.id == min(loop):
                    fail(
                        record.where,
                        "the supersede chain closes a loop: {}. "
                        "A record replaced by something it "
                        "replaced leaves no decision in force".format(
                            " -> ".join(loop + [following.id])
                        ),
                    )
                break
            seen.append(following.id)
            current = following


def imports_agents_md(text):
    """Whether this CLAUDE.md hands Claude Code the AGENTS.md beside it.

    Takes the file's text, not its `rule_body`: that collapses the whole file to
    one line, so asking it for a line of its own would be the strict form again
    under a new name.

    A line that is exactly `@AGENTS.md` does that, and what the file adds after
    it does not undo it -- the root `CLAUDE.md` imports and then adds its Claude
    Code section. The two cases this still refuses carry no such line: an empty
    `CLAUDE.md`, which hands Claude Code nothing, and one importing some other
    file, which hands it the wrong thing.
    """
    return any(
        line.strip() == "@AGENTS.md"
        for line in strip_fences(strip_frontmatter(text)).splitlines()
    )


def check_paired_rules(rules, repo):
    """The paired-file fallback in references/wiring.md, kept honest.

    Where a nested `CLAUDE.md` import does not work, the documented fallback is
    the same rule text in both files. That only serves its purpose while the two
    agree: otherwise Claude Code and Codex are handed different constraints from
    one directory, and nothing else would notice.

    The sibling is read from disk rather than looked up among the rules. A copy
    that lost its `Source:` line is not collected as a rule, and that is exactly
    the copy most likely to have drifted.
    """
    checked = set()
    for rule in rules:
        if rule.path.name not in ("AGENTS.md", "CLAUDE.md"):
            continue
        directory = rule.path.parent
        if directory in checked:
            continue
        other_name = "CLAUDE.md" if rule.path.name == "AGENTS.md" else "AGENTS.md"
        sibling = directory / other_name
        if not sibling.is_file():
            continue
        checked.add(directory)
        sibling_text = read(sibling)
        other = rule_body(sibling_text)
        # Only a CLAUDE.md may be the import: an AGENTS.md holding `@AGENTS.md`
        # imports itself and leaves Codex with no constraint at all.
        if imports_agents_md(sibling_text if other_name == "CLAUDE.md" else rule.text):
            continue
        if other != rule.body:
            fail(
                (directory / "CLAUDE.md").relative_to(repo).as_posix(),
                "does not carry the same rule as {} in the same directory. "
                "The paired-file fallback works only while both say the same "
                "thing, and the exempt form is a CLAUDE.md carrying "
                "`@AGENTS.md` on a line of its own. An empty one, one importing another "
                "file, or an AGENTS.md importing itself leaves one of the two "
                "hosts with no constraint at all".format(
                    (directory / "AGENTS.md").relative_to(repo).as_posix()
                ),
            )


def check_rule_fields(records, repo):
    """A named rule has to exist, and only a standing decision owns one."""
    for record in records:
        for named in record.rules:
            if not (repo / named).is_file():
                fail(record.where, f"rule points at '{named}', which does not exist")
            elif record.status != "accepted":
                fail(
                    record.where,
                    f"status is '{record.status}' but it still owns the rule "
                    f"'{named}'; a rule states what holds now",
                )


def check_backlinks(records, rules, repo):
    """Both halves of the backlink, held against each other as two sets.

    Checking only that each end resolves lets record A point at a rule that
    cites record B, with every individual check passing -- and then superseding
    A leaves B's rule standing, which is the failure the two-way link exists to
    prevent.
    """
    by_where = {record.where: record for record in records}
    where_by_id = {record.id: record.where for record in records}
    declared, cited = set(), set()

    for record in records:
        if record.status != "accepted":
            continue
        for named in record.rules:
            if (repo / named).is_file():
                declared.add((record.id, normalize(repo, named)))

    for rule in rules:
        if not rule.source:
            fail(rule.where, "no 'Source:' line naming the record it comes from")
            continue
        record = by_where.get(normalize(repo, rule.source))
        if record is None:
            fail(rule.where, f"Source names '{rule.source}', which is not a record")
        elif record.status != "accepted":
            fail(
                rule.where,
                f"Source names '{rule.source}', whose status is '{record.status}'; "
                "supersede the rule along with the record",
            )
        else:
            cited.add((record.id, rule.where))

    for record_id, rule_path in sorted(cited - declared):
        fail(
            rule_path,
            f"Source names record '{record_id}', which does not name this "
            "file back in its rule field",
        )
    for record_id, rule_path in sorted(declared - cited):
        fail(
            where_by_id.get(record_id, record_id),
            f"rule names '{rule_path}', which does not cite this record back. A rule "
            "lives in .claude/rules/ or in a directory's AGENTS.md and ends "
            "with its 'Source:' line",
        )


def check_glob_scope(records, rules, decisions_rel):
    """Every rule is scoped, and none is scoped so wide it reaches the records.

    The patterns are collected across all rules and each compiled once: the
    same `**/*.ts` in five rules is one question, and the passing case is the
    expensive one because `any()` only short-circuits on a match.
    """
    for rule in rules:
        if rule.in_rules_dir and not rule.paths:
            fail(
                rule.where,
                "no 'paths:' frontmatter, so this loads in every "
                "session at the priority of the project CLAUDE.md. "
                "A derived rule is always scoped; a rule that "
                "applies everywhere is a line in AGENTS.md instead",
            )

    where = [record.where for record in records]
    patterns = {}
    for rule in rules:
        for pattern in rule.paths:
            patterns.setdefault(pattern, []).append(rule.where)
    for pattern, holders in sorted(patterns.items()):
        matcher = glob_to_regex(pattern)
        if any(matcher.match(path) for path in where):
            for holder in holders:
                fail(
                    holder,
                    f"the glob '{pattern}' covers {decisions_rel}/. Records must never "
                    "load as rules: the superseded ones would come "
                    "back into every session",
                )


def check_length(record):
    """The section vocabulary and the word budgets."""
    sections = outline(record.text)
    level_two = [title for level, title, _ in sections if level == 2]
    # Level two only: a `### Confirmation` nested inside a short record's
    # Context is not what makes a record a full one.
    is_full = any(title in FULL_ONLY for title in level_two)
    limits = FULL_LIMITS if is_full else SHORT_LIMITS
    allowed = FULL_SECTIONS if is_full else SHORT_SECTIONS
    escape = (
        "split the decision, or this is two of them"
        if is_full
        else "say less, or take the full template, assets/templates/full.md"
    )

    if len(record.titles) != 1:
        fail(
            record.where,
            f"{len(record.titles)} level-one headings; a "
            f"record has exactly one, and it is what the index "
            f"shows",
        )
    if len(record.title.split()) > TITLE_WORDS:
        fail(
            record.where,
            f"the title is {len(record.title.split())} words, "
            f"over {TITLE_WORDS}; it names the decision, it "
            f"does not summarize it",
        )

    required = FULL_SECTIONS if is_full else SHORT_SECTIONS
    for title in required:
        if title not in level_two:
            fail(
                record.where,
                "no '## {}' section; the {} template's required sections are {}".format(
                    title, "full" if is_full else "short", ", ".join(required)
                ),
            )
    for title in sorted(set(level_two)):
        if level_two.count(title) > 1:
            fail(
                record.where,
                f"'{title}' appears {level_two.count(title)} "
                f"times. Each section occurs once, or its word "
                f"budget is simply split across the copies",
            )

    options = []
    inside_options = False
    # Whatever sits between the frontmatter and the title belongs to no
    # section, so no per-section cap reaches it. It still counts.
    preamble = []
    for line in strip_fences(strip_frontmatter(record.text)).splitlines():
        if HEADING_RE.match(line):
            break
        preamble.append(line)
    total = count_words(preamble)
    for index, (level, title, lines) in enumerate(sections):
        total += count_words(lines)
        if level == 3 and inside_options:
            options.append((title, block_words(sections, index)))
        if level != 2:
            continue
        words = block_words(sections, index)
        inside_options = title == "Considered options"
        if title not in allowed:
            fail(
                record.where,
                "'{}' is not a section of the {} template, so no "
                "budget covers it. Use one of: {}".format(
                    title, "full" if is_full else "short", ", ".join(allowed)
                ),
            )
            continue
        if title in limits and words > limits[title]:
            fail(
                record.where,
                f"{title} is {words} words, over the "
                f"{limits[title]} a "
                f"{'full' if is_full else 'short'} record "
                f"allows: {escape}",
            )
        if title == "Decision drivers":
            drivers = bullets(lines)
            if not drivers:
                fail(
                    record.where,
                    f"Decision drivers carries no bullet of "
                    f"its own, so nothing in it is held to the "
                    f"{PER_DRIVER} words a driver gets. One "
                    f"bullet per driver",
                )
            if len(drivers) > MAX_DRIVERS:
                fail(
                    record.where,
                    f"{len(drivers)} decision drivers, over "
                    f"{MAX_DRIVERS}. Past that they are not "
                    f"what decided it, they are everything "
                    f"that was true",
                )
            for number, driver in enumerate(drivers, 1):
                if count_words([driver]) > PER_DRIVER:
                    fail(
                        record.where,
                        f"decision driver {number} is "
                        f"{count_words([driver])} words, over "
                        f"{PER_DRIVER}. A driver is a line, "
                        f"not an argument",
                    )

    if is_full and "Considered options" in level_two and not options:
        fail(
            record.where,
            f"Considered options carries no '### ' option of "
            f"its own, so nothing in it is held to the "
            f"{PER_OPTION} words an option gets. One heading "
            f"per option considered",
        )
    for title, words in options:
        if words > PER_OPTION:
            fail(
                record.where,
                f"the option '{title}' is {words} words, "
                f"over {PER_OPTION}. It answers why the option "
                f"lost, it does not re-explain what it is",
            )

    ceiling = (
        FULL_BASE + FULL_PER_OPTION * max(len(options), 1) if is_full else SHORT_TOTAL
    )
    if total > ceiling:
        fail(record.where, f"{total} words in all, over {ceiling}: {escape}")


def check(records, rules, repo, decisions):
    by_id = check_identity(records)
    check_supersede(records, by_id)
    check_rule_fields(records, repo)
    check_supersede_chains(records, by_id)
    check_paired_rules(rules, repo)
    check_backlinks(records, rules, repo)
    check_glob_scope(records, rules, decisions.relative_to(repo).as_posix())
    for record in records:
        if not record.frontmatter_error:
            check_length(record)


# --- the index -------------------------------------------------------------


def render_index(records):
    def cell(text):
        """A pipe in a title opens a column; the index would render wrong
        while --check still called it current."""
        return text.replace("|", "\\|")

    def link(record):
        return f"[{cell(record.title)}]({record.relative})"

    lines = [
        GENERATED,
        "",
        "# Decisions",
        "",
        (
            "One line per record. Read this before deciding something new, so "
            "a fresh decision does not quietly contradict a standing one. "
            "Records are never rewritten: a decision that stops holding is "
            "superseded and moves to *History*."
        ),
        "",
    ]

    def section(title, columns, rows):
        if rows:
            lines.extend(
                [
                    "## " + title,
                    "",
                    "| " + " | ".join(columns) + " |",
                    "| " + " | ".join([":---"] * len(columns)) + " |",
                ]
                + rows
                + [""]
            )

    def pick(*statuses):
        return sorted(
            (r for r in records if r.status in statuses),
            key=lambda r: r.id or r.path.stem,
            reverse=True,
        )

    by_id = {record.id: record for record in records if record.id}

    section(
        "In force",
        ["Decision", "Tags", "Rule"],
        [
            "| {} | {} | {} |".format(
                link(r),
                cell(", ".join(r.tags)) or "—",
                cell(", ".join(f"`{name}`" for name in r.rules)) or "—",
            )
            for r in pick("accepted")
        ],
    )
    section(
        "Proposed",
        ["Decision", "Waiting on", "Tags"],
        [
            "| {} | {} | {} |".format(
                link(r), cell(r.waiting_on) or "—", cell(", ".join(r.tags)) or "—"
            )
            for r in pick("proposed")
        ],
    )
    section(
        "History",
        ["Decision", "Status", "Replaced by"],
        [
            "| {} | {} | {} |".format(
                link(r),
                r.status,
                link(by_id[r.superseded_by]) if r.superseded_by in by_id else "—",
            )
            for r in pick("superseded", "rejected")
        ],
    )

    if not records:
        lines.extend(["No records yet.", ""])
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="regenerate the index")
    mode.add_argument(
        "--check",
        action="store_true",
        help="report every problem and exit 1 if there is one",
    )
    parser.add_argument(
        "--root",
        # Hostwarden keeps its records in docs/adr/, the second of its
        # changes to this file (docs/adr/20260924-cite-only-rules.md).
        default="docs/adr",
        help="the decisions directory (default: docs/adr)",
    )
    parser.add_argument(
        "--repo",
        default=".",
        help="the repository root (default: the working directory)",
    )
    arguments = parser.parse_args()

    repo = Path(arguments.repo).resolve()
    decisions = (repo / arguments.root).resolve()
    if not decisions.is_dir():
        print(f"{arguments.root}/ does not exist", file=sys.stderr)
        return 1
    if repo not in decisions.parents:
        # Several checks state a record's location relative to the repository,
        # and a rule cites one by a repository-relative path, so a corpus
        # outside the tree can be neither reported nor cited. Said here rather
        # than raised out of the first `relative_to` that meets it.
        print(
            f"{arguments.root}/ is outside {arguments.repo}/; the records live in the repository they "
            "bind",
            file=sys.stderr,
        )
        return 1

    records = collect_records(decisions, repo)
    index_path = decisions / "README.md"
    index = render_index(records)

    if arguments.write:
        index_path.write_text(index, encoding="utf-8")
        print(
            f"wrote {index_path.relative_to(repo).as_posix()} "
            f"({len(records)} record{plural(len(records))})"
        )
        return 0

    check(records, collect_rules(repo, decisions), repo, decisions)
    index_where = index_path.relative_to(repo).as_posix()
    if not index_path.is_file():
        fail(index_where, f"missing; run `{rerun_command(repo)}`")
    elif read(index_path) != index:
        fail(index_where, f"is out of date; run `{rerun_command(repo)}`")

    if problems:
        sys.stderr.write("\n".join("  " + line for line in problems) + "\n")
        sys.stderr.write(f"\n{len(problems)} problem(s).\n")
        return 1
    print(f"{len(records)} record{plural(len(records))}, index current, no problems")
    return 0


if __name__ == "__main__":
    sys.exit(main())
