// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Autogenerated from the docs/ folder structure. A page's position
 * comes from its own `sidebar_position` front matter, and a
 * subfolder's from its `_category_.json` — nothing is listed here
 * by hand.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
