// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * One sidebar per navbar section, each autogenerated from its own
 * folder under docs/. A page's position comes from its own
 * `sidebar_position` front matter, and a subfolder's from its
 * `_category_.json` — nothing is listed here by hand.
 *
 * `development` is the only section about Hostwarden's own source;
 * every other one is written for the admin who runs it.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  start: [{type: 'autogenerated', dirName: 'getting-started'}],
  features: [{type: 'autogenerated', dirName: 'features'}],
  memory: [{type: 'autogenerated', dirName: 'memory'}],
  safety: [{type: 'autogenerated', dirName: 'safety'}],
  running: [{type: 'autogenerated', dirName: 'running-it'}],
  reference: [{type: 'autogenerated', dirName: 'reference'}],
  development: [{type: 'autogenerated', dirName: 'development'}],
};

export default sidebars;
