# tests/hooks/guard-mode/containers.sh — containers and lab VMs as
# scripts/lab.sh starts them, and the rest of development. Sourced
# by tests/hooks/guard-mode.sh, in the order its PARTS lists, into
# the one shell every part shares; never run on its own.
# shellcheck shell=sh disable=SC2034 # read by the parts after it

cmd pass "$DEV" 'docker run --detach --rm --init --name hwlab-x-debian --label hostwarden.lab=x --security-opt no-new-privileges docker.io/library/debian:13 sh -c "sleep 21600"'
cmd pass "$DEV" 'podman run --rm -it docker.io/library/alpine:3.24 sh'
cmd pass "$DEV" 'docker run --rm -v cache:/var/cache/apt debian:13 true'
cmd pass "$DEV" 'docker run --rm -v /data debian:13 true'
cmd pass "$DEV" 'docker run --rm --mount type=volume,src=cache,dst=/c debian:13 true'
cmd pass "$DEV" 'docker run --rm --mount type=tmpfs,dst=/t debian:13 true'
cmd deny "$DEV" 'docker exec -i hwlab-x-debian apt-get -s install nginx'
cmd pass "$DEV" 'docker ps --filter label=hostwarden.lab=x'
cmd deny "$DEV" 'docker rm -f $(docker ps -aq --filter label=hostwarden.lab=x)'
cmd pass "$DEV" 'docker -v'
cmd pass "$DEV" 'docker run --rm --privileged=false debian:13 true'
cmd pass "$DEV" 'grep -rn "docker run" docs/'
# An engine counts as a command, not as a word in one.
cmd pass "$DEV" 'rg "docker exec" docs/'
cmd pass "$DEV" 'git commit -m "fix docker rm handling"'
cmd deny "$DEV" 'bash -lc "docker rm -f other-project"'
cmd pass "$DEV" 'bash -s -- docker rm < script.sh'
cmd pass "$DEV" 'sh ./lab.sh docker rm'
cmd deny "$DEV" 'timeout 60 docker exec other-project true'
cmd deny "$DEV" 'timeout -s KILL 5 docker exec other-project true'
cmd deny "$DEV" 'xargs -I x docker rm x < ids.txt'
cmd deny "$DEV" 'if docker rm other-project; then echo gone; fi'
cmd deny "$DEV" 'xargs -n1 docker rm < ids.txt'
cmd deny "$DEV" 'find . -name x -exec docker rm {} \;'
cmd deny "$DEV" 'x=$(docker run --rm --privileged debian:13 true)'
cmd deny "$DEV" 'echo "$(docker run --rm -v /:/h debian:13 true)"'
cmd deny "$DEV" 'for c in a b; do docker rm "$c"; done'
cmd deny "$DEV" '(docker rm -f other-project)'
cmd deny "$DEV" 'x=$(orb create debian y)'
cmd pass "$DEV" 'find . -name "*.md" -exec grep -l docker {} +'
cmd pass "$DEV" 'gh pr comment 5 --body "docker rm other"'
cmd pass "$DEV" 'scripts/lab.sh exec debian -- sh -c "ls -v /etc"'
cmd deny "$DEV" 'docker run --rm --privileged debian:13 true'
cmd deny "$DEV" 'docker run --rm -v /:/host debian:13 true'
cmd deny "$DEV" 'docker run --rm -v "$HOME:/h" debian:13 true'
cmd deny "$DEV" 'docker run --rm -v ~/.ssh:/k debian:13 true'
cmd deny "$DEV" 'docker run --rm -v ./src:/src debian:13 true'
cmd deny "$DEV" 'docker run --rm -v "$(pwd)":/src debian:13 true'
cmd deny "$DEV" 'docker run --rm -v "${PWD}:/src" debian:13 true'
cmd deny "$DEV" 'docker run --rm -v `pwd`:/src debian:13 true'
cmd deny "$DEV" 'docker run --rm --volume=${HOME}/x:/x debian:13 true'
cmd deny "$DEV" 'docker run --rm --mount src=$(pwd),dst=/x,type=bind debian:13 true'
cmd deny "$DEV" 'docker run --rm -itv /etc:/e debian:13 sh'
cmd deny "$DEV" 'docker run --rm -v/var/run/docker.sock:/var/run/docker.sock debian:13 true'
cmd deny "$DEV" 'docker run --rm --volume=/srv:/srv debian:13 true'
cmd deny "$DEV" 'docker run --rm --mount type=bind,src=/,dst=/h debian:13 true'
cmd deny "$DEV" 'docker run --rm --mount=type=volume,dst=/h,volume-opt=device=/home,volume-opt=o=bind debian:13 true'
cmd deny "$DEV" 'docker run --rm --pid=host debian:13 true'
cmd deny "$DEV" 'docker run --rm --net host debian:13 true'
cmd deny "$DEV" 'docker run --rm --network=host debian:13 true'
cmd deny "$DEV" 'podman run --rm --userns=host debian:13 true'
cmd deny "$DEV" 'docker run --rm --ipc host debian:13 true'
cmd deny "$DEV" 'docker run --rm --device /dev/sda debian:13 true'
cmd deny "$DEV" 'docker run --rm --cap-add=SYS_ADMIN debian:13 true'
cmd deny "$DEV" 'docker run --rm --security-opt seccomp=unconfined debian:13 true'
cmd deny "$DEV" 'podman run --rm --security-opt label=disable debian:13 true'
cmd deny "$DEV" 'docker run --rm --volumes-from other debian:13 true'
cmd deny "$DEV" 'podman run --rm --rootfs /srv/root true'
cmd deny "$DEV" 'docker create --privileged debian:13'
cmd deny "$DEV" 'docker container run --rm --privileged debian:13 true'
cmd deny "$DEV" 'docker --context orbstack run --rm --privileged debian:13 true'
cmd deny "$DEV" '/usr/local/bin/docker run --rm --privileged debian:13 true'
cmd deny "$DEV" 'nerdctl run --rm --privileged debian:13 true'
cmd deny "$DEV" "sh -c 'docker run --rm --privileged debian:13 true'"
cmd deny "$DEV" 'true && docker run --rm --pid=host debian:13 true'
cmd deny "$DEV" 'docker exec --privileged hwlab-x-debian true'
cmd deny "$DEV" 'docker compose up -d'
cmd deny "$DEV" 'docker-compose run web'
cmd deny "$DEV" 'podman kube play pod.yaml'
cmd deny "$DEV" 'docker volume create --opt type=none --opt device=/home --opt o=bind h'
cmd pass "$DEV" 'docker volume create cache'
# Reading, pulling and building pass; every other verb could reach
# or change a container that is not the lab's.
cmd pass "$DEV" 'docker images'
cmd pass "$DEV" 'docker image ls'
cmd pass "$DEV" 'docker pull docker.io/library/debian:13'
cmd pass "$DEV" 'docker inspect hwlab-x-debian --format "{{.Config.Image}}"'
cmd pass "$DEV" 'docker logs hwlab-x-debian'
cmd pass "$DEV" 'docker build -t x .'
cmd pass "$DEV" 'docker system df'
cmd pass "$DEV" 'docker compose ps'
cmd pass "$DEV" 'podman --help'
cmd deny "$DEV" 'docker exec -it other-project sh'
cmd deny "$DEV" 'docker container exec other-project sh'
cmd deny "$DEV" 'docker attach other-project'
cmd deny "$DEV" 'docker rm -f other-project'
cmd deny "$DEV" 'docker stop other-project'
cmd deny "$DEV" 'docker system prune -af'
cmd deny "$DEV" 'docker image rm debian:13'
cmd deny "$DEV" 'docker volume rm data'
cmd deny "$DEV" 'podman machine stop'
cmd deny "$DEV" 'docker cp other-project:/etc/shadow .'
cmd deny "$DEV" 'docker compose down'
# Only the local engine: another one is a server.
cmd deny "$DEV" 'docker --context production ps'
cmd deny "$DEV" 'docker -H tcp://server1.example.com:2375 ps'
cmd deny "$DEV" 'docker --host=ssh://root@server1.example.com ps'
cmd deny "$DEV" 'podman --remote ps'
cmd deny "$DEV" 'podman --connection prod ps'
cmd deny "$DEV" 'DOCKER_HOST=tcp://server1.example.com:2375 docker ps'
cmd deny "$DEV" 'export DOCKER_HOST=ssh://root@server1.example.com; docker ps'
cmd deny "$DEV" 'CONTAINER_HOST=ssh://root@server1.example.com podman ps'
cmd pass "$DEV" 'echo "$DOCKER_HOST"'
# No port on this machine, no build result written to it.
cmd deny "$DEV" 'docker run --rm -p 8080:80 nginx'
cmd deny "$DEV" 'docker run --rm -P nginx'
cmd deny "$DEV" 'docker run --rm -dp 8080:80 nginx'
cmd deny "$DEV" 'docker run --rm --publish=8080:80 nginx'
cmd deny "$DEV" 'docker run --rm --publish-all nginx'
cmd deny "$DEV" 'docker build --output type=local,dest=/tmp/out .'
cmd deny "$DEV" 'docker build -o out .'
cmd deny "$DEV" 'docker buildx build --output=type=tar,dest=x.tar .'
cmd deny "$DEV" 'docker buildx build --cache-to type=local,dest=/tmp/c .'
cmd pass "$DEV" 'docker build -t x --pull .'
cmd deny "$DEV" 'docker build --iidfile /tmp/id .'
cmd deny "$DEV" 'podman build --iidfile=id.txt .'
cmd deny "$DEV" 'docker buildx build --metadata-file meta.json .'
# No host file or host variable read into a container or a build.
cmd deny "$DEV" 'docker run --rm --env-file ~/.env debian:13 env'
cmd deny "$DEV" 'docker run --rm --env-file=.env debian:13 env'
cmd deny "$DEV" 'podman run --rm --label-file labels debian:13 true'
cmd deny "$DEV" 'docker run --rm --cidfile /tmp/id debian:13 true'
cmd deny "$DEV" 'docker run --rm -e AWS_SECRET_ACCESS_KEY debian:13 env'
cmd deny "$DEV" 'docker run --rm --env GITHUB_TOKEN debian:13 env'
cmd deny "$DEV" 'docker run --rm -eGITHUB_TOKEN debian:13 env'
cmd pass "$DEV" 'docker run --rm -e LANG=C.UTF-8 --env TZ=UTC debian:13 date'
cmd deny "$DEV" 'docker build --secret id=aws,src=/home/alice/.aws/credentials .'
cmd deny "$DEV" 'docker buildx build --ssh default .'
# Another container's namespace, and a host path in a podman build.
cmd deny "$DEV" 'docker run --rm --pid=container:other-project debian:13 ps'
cmd deny "$DEV" 'docker run --rm --network container:other-project debian:13 true'
cmd deny "$DEV" 'podman run --rm --ipc=ns:/proc/1/ns/ipc debian:13 true'
cmd pass "$DEV" 'docker run --rm --network=none debian:13 true'
cmd deny "$DEV" 'podman build -v ~/.ssh:/secrets .'
cmd deny "$DEV" 'podman build --volume=/home/alice:/h .'
cmd pass "$DEV" 'podman build -t x .'
# The standalone compose tools follow the same verbs.
cmd deny "$DEV" 'docker-compose down -v'
cmd deny "$DEV" 'podman-compose rm -f'
cmd deny "$DEV" 'docker-compose -f other.yml up -d'
cmd pass "$DEV" 'docker-compose ps'
cmd pass "$DEV" 'docker-compose -f lab.yml config'
cmd pass "$DEV" 'docker run --rm --pid=private --pull=missing debian:13 true'
# Lab VMs: created and deleted from here, used only by a test clone.
cmd deny "$DEV" 'orb create --isolated debian:13 hwlab-x-debian'
cmd deny "$DEV" 'orbctl add debian x'
cmd deny "$DEV" 'limactl create template:debian-13'
cmd pass "$DEV" 'scripts/lab.sh vm up debian --ops ~/hostwarden-test'
cmd deny "$DEV" 'orb delete --force hwlab-x-debian'
cmd pass "$DEV" 'orb list'
cmd pass "$DEV" 'orb --help'
cmd pass "$DEV" 'orbctl status'
cmd pass "$DEV" 'orb info hwlab-x-debian'
cmd pass "$DEV" 'orbctl'
cmd deny "$DEV" 'limactl start x'
cmd deny "$DEV" 'limactl start'
cmd pass "$DEV" 'orb start'
cmd deny "$DEV" 'orb start other-vm'
cmd deny "$DEV" 'orbctl start -a'
cmd deny "$DEV" 'orb rm other-vm'
cmd deny "$DEV" 'orbctl delete -f other-vm'
cmd deny "$DEV" 'orb reset'
cmd deny "$DEV" 'orb stop other-vm'
cmd deny "$DEV" 'limactl delete --force other-vm'
cmd deny "$DEV" 'limactl stop other-vm'
cmd deny "$DEV" 'limactl factory-reset other-vm'
cmd pass "$DEV" 'limactl list'
cmd pass "$DEV" 'grep -rn orb docs/'
cmd pass "$DEV" 'git commit -m "lab: lima and orb"'
cmd deny "$DEV" 'orb'
cmd deny "$DEV" 'orb uname -a'
cmd deny "$DEV" 'orb -m hwlab-x-debian -u root systemctl status'
cmd deny "$DEV" 'orb run uname -a'
cmd deny "$DEV" 'orbctl run -m x uname -a'
cmd deny "$DEV" 'orb push notes.txt'
cmd deny "$DEV" 'limactl shell x uname -a'
cmd deny "$DEV" 'limactl copy notes.txt x:/tmp/'
cmd deny "$DEV" 'lima uname -a'
cmd deny "$DEV" 'FOO=1 orb uname -a'
cmd deny "$DEV" 'true
orb uname -a'
cmd pass "$DEV" 'grep -rn forbidden rules/ | grep -v absorb'
cmd pass "$DEV" 'echo climate orbit'
mon deny "$DEV" 'docker run --rm -v /:/host debian:13 true'
mon deny "$DEV" 'orb -m hwlab-x-debian journalctl -f'
mon pass "$DEV" 'docker logs -f hwlab-x-debian'
# A shell with -c is a launcher: its command string is read.
mon deny "$DEV" "sh -c 'ssh server1.example.com uptime'"
mon pass "$DEV" 'bash -s -- ssh server1.example.com < probe'
