# lib/hostwarden-map/overview.sh — the overview, memory/README.md: the
# one page a person reads first, each line leading on to a map or a
# memory file. Sourced by bin/hostwarden-map, in the order its PARTS
# lists, into the one shell every part shares; never run on its own.
#
# It summarises and links, and never repeats a host's detail: a
# count, a date and a link per line, the facts staying where memory
# keeps them. It reads only what the parts before it read, plus each
# listed host's changelog.log, and lists only the hosts $HOSTS does,
# so a personal host (classify.sh) never reaches it either.
# shellcheck shell=sh

OVERVIEW=$M/README.md
OV_MARK='<!-- Generated by bin/hostwarden-map from memory/. Do not edit by hand. -->'
# The issues that add the facts a section waits for, as full links:
# this page lives in the workspace's repository, where a bare "#284"
# would point at that repository's own issue.
OV_ISSUES=https://github.com/hostwarden/hostwarden/issues

# hosts_n <n> -- "1 host" or "<n> hosts".
hosts_n() { if [ "$1" -eq 1 ]; then echo "1 host"; else echo "$1 hosts"; fi; }

# not_recorded <what> <question> <issue> -- the one line a section
# whose facts no rule records yet prints instead.
not_recorded() {
  printf 'Not recorded yet: %s. Filled by %s ([hostwarden#%s](%s/%s)).\n' \
    "$1" "$2" "$3" "$OV_ISSUES" "$3"
}

# --- the changelogs: each host's last housekeeping run and security
#     audit, and its newest entry of any kind -----------------------
#
# RUNS:    <host> TAB <kind> TAB <date> TAB <critical> TAB <warn>
#          TAB <info>, the newest entry of each kind
# CONTACT: <host> TAB <date>, the newest entry of any kind
#
# An entry starts with "[YYYY-MM-DD HH:MM]" in column 1, its headline
# running on over the unindented lines after it; the indented lines
# are its detail (rules/changelog.md → Local Changelog). A run's
# headline is the journal's summary line: "Housekeeping: 1 CRITICAL,
# 2 WARN, all services OK" by hand, "read-only: housekeeping: 2 WARN
# — <text>" from bin/hostwarden-fleet-run, "Security audit: 1 WARN,
# 1 INFO". Only the counts before a " — " are read, so a finding's
# own text never adds to them. A fleet run that did not reach the
# host still writes its entry, its Detail: line then ending "the
# host was not read"; such an entry is neither contact nor a run.
RUNS="$WORK/runs.tsv"
CONTACT="$WORK/contact.tsv"
: >"$RUNS"; : >"$CONTACT"
set --
while IFS="$US" read -r h _; do
  [ -n "$h" ] && [ -f "$M/machines/$h/changelog.log" ] \
    && set -- "$@" "$M/machines/$h/changelog.log"
done <"$HOSTS.us"
if [ $# -gt 0 ]; then
  awk -v runs="$RUNS" -v contact="$CONTACT" '
    function count(s, sev) {
      if (match(s, "[0-9]+ " sev)) return substr(s, RSTART, RLENGTH) + 0
      return 0
    }
    # unbracket <text> -- <text> without the "[...]" it starts with.
    function unbracket(t,   i) {
      if (substr(t, 1, 1) == "[" && (i = index(t, "]")) > 0) t = substr(t, i + 1)
      sub(/^[ \t]+/, "", t)
      return t
    }
    function flush(   t, lt, kind, s, k, d) {
      if (stamp == "" || noread) { stamp = ""; head = ""; inhead = 0; noread = 0; return }
      d = substr(stamp, 1, 10)
      if (d > last[h]) last[h] = d
      t = unbracket(unbracket(head))
      sub(/^read-only:[ \t]*/, "", t)
      lt = tolower(t)
      kind = ""
      if (lt ~ /^housekeeping:/) kind = "housekeeping"
      else if (lt ~ /^security audit:/) kind = "security audit"
      if (kind != "") {
        s = t; sub(/^[^:]*:/, "", s); sub(/ — .*/, "", s)
        k = h SUBSEP kind
        if (!(k in when) || stamp >= when[k]) {
          when[k] = stamp
          line[k] = h "\t" kind "\t" substr(stamp, 1, 10) "\t" \
            count(s, "CRITICAL") "\t" count(s, "WARN") "\t" count(s, "INFO")
        }
      }
      stamp = ""; head = ""; inhead = 0; noread = 0
    }
    FNR == 1 { flush(); h = FILENAME; sub(/\/changelog\.log$/, "", h); sub(/.*\//, "", h) }
    /^\[[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9:]+\]/ {
      flush(); stamp = substr($0, 2); sub(/\].*/, "", stamp)
      head = $0; inhead = 1; next
    }
    inhead && /^[^ \t\[]/ { head = head " " $0; next }
    /^[ \t]+Detail: fleet read .*the host was not read\.$/ { noread = 1 }
    { inhead = 0 }
    END {
      flush()
      for (k in line) print line[k] > runs
      for (x in last) print x "\t" last[x] > contact
    }' "$@" || die "a host's changelog.log could not be read"
fi

# --- the page -------------------------------------------------------
{
  printf '%s\n' "$OV_MARK"
  echo
  echo "# Workspace"
  echo
  echo "Generated by \`bin/hostwarden-map\` from memory, never edited by"
  echo "hand. Each line leads on to a map or a memory file, where the"
  echo "facts are kept; this page only counts and links."
  echo

  # --- sites --------------------------------------------------------
  echo "## Sites"
  echo
  # One pass: <site> TAB <hosts> per declared site, and the number of
  # hosts on no declared site in a file of its own.
  awk -F '\t' -v f="$SITES" -v nonefile="$WORK/site-none" '
    BEGIN { while ((getline l < f) > 0) { split(l, a, "\t"); if (a[1] != "") n[a[1]] = 0 } }
    ($2 in n) { n[$2]++; next }
    { none++ }
    END { for (s in n) print s "\t" n[s]; print none + 0 > nonefile }
  ' "$HOSTS" | LC_ALL=C sort >"$WORK/site-counts.tsv"
  if [ -s "$SITES" ]; then
    while IFS='	' read -r s n; do
      [ -n "$s" ] || continue
      printf -- '- [%s](maps/sites/%s.md) — %s\n' "$s" "$(slug_sh "$s")" "$(hosts_n "$n")"
    done <"$WORK/site-counts.tsv"
  else
    echo "- No site recorded in [topology.md](topology.md) yet."
  fi
  n=$(cat "$WORK/site-none")
  [ "$n" -gt 0 ] \
    && printf -- '- No site on record: %s — [WAN](maps/wan.md)\n' "$(hosts_n "$n")"
  echo
  echo "Every map, clusters and hypervisors included:"
  echo "[maps/README.md](maps/README.md)."
  echo

  # --- what no rule records yet ------------------------------------
  echo "## Services"
  echo
  not_recorded "the services the fleet provides and the hosts behind each" \
    "the question which services the fleet provides" 284
  echo
  echo "## Critical hosts"
  echo
  not_recorded "criticality, owner and recovery target" \
    "the onboarding question for owner, criticality and recovery target" 283
  echo

  # --- open findings ------------------------------------------------
  echo "## Open findings"
  echo
  echo "Counts from each host's last housekeeping run and security audit,"
  echo "as its changelog records them."
  echo
  # Worst first: the most CRITICAL, then the most WARN, then by name.
  LC_ALL=C sort "$RUNS" | awk -F '\t' '
    { c[$1] += $4; w[$1] += $5
      part = $2 " " $3 ": "
      sep = ""
      if ($4) { part = part sep $4 " CRITICAL"; sep = ", " }
      if ($5) { part = part sep $5 " WARN"; sep = ", " }
      if ($6) { part = part sep $6 " INFO"; sep = ", " }
      if (sep == "") part = part "no findings"
      txt[$1] = (txt[$1] == "" ? "" : txt[$1] " · ") part }
    END { for (h in c) if (c[h] + w[h] > 0) printf "%d\t%d\t%s\t%s\n", c[h], w[h], h, txt[h] }
  ' | LC_ALL=C sort -t '	' -k1,1nr -k2,2nr -k3,3 >"$WORK/open.tsv"
  if [ -s "$WORK/open.tsv" ]; then
    while IFS='	' read -r _ _ h txt; do
      printf -- '- [%s](machines/%s/changelog.log) — %s\n' "$h" "$h" "$txt"
    done <"$WORK/open.tsv"
  else
    echo "- No CRITICAL or WARN in the last runs."
  fi
  n=$(awk -F '\t' '$1 == "WARN" { n++ } END { print n + 0 }' "$FINDINGS")
  [ "$n" -gt 0 ] \
    && printf -- '- Network: %s WARN in [topology.md](topology.md) — [WAN](maps/wan.md)\n' "$n"
  cut -f1 "$HOSTS" >"$WORK/ov-hosts"; cut -f1 "$RUNS" >"$WORK/ov-run-hosts"
  n=$(unplaced_of "$WORK/ov-hosts" "$WORK/ov-run-hosts" | wc -l | tr -d ' ')
  [ "$n" -gt 0 ] && printf -- '- No housekeeping run or audit on record: %s\n' "$(hosts_n "$n")"
  echo

  # --- more of what no rule records yet ----------------------------
  echo "## Expiring within 90 days"
  echo
  not_recorded "end of life, certificates, subscriptions and warranties with their dates" \
    "the lifecycle dates housekeeping reads and the question for the rest" 285
  echo
  echo "## Backups without a tested restore"
  echo
  not_recorded "what a backup covers and when a restore last worked" \
    "the question when a restore was last tested" 286
  echo

  # --- hosts not connected lately ----------------------------------
  # A host an operations host reads (a Fleet read: line) is due every
  # night, and late after two days without contact; any other host
  # after 90, the age rules/machine-memory.md → Onboarded and stale
  # lines calls stale. Contact is the later of Last connected: and
  # the host's newest changelog entry, since a nightly read-only run
  # writes the latter alone.
  echo "## Not connected lately"
  echo
  echo "A host that fleet read reaches is due every night and listed"
  echo "after 2 days without contact; any other host after 90."
  echo
  # One pass: <host> TAB <Last connected:> TAB <fleet read 0|1> TAB
  # <newest changelog date> for every host the maps draw. Fleet read
  # counts only once the key line is present, the same line
  # bin/hostwarden-fleet-run selects its hosts by.
  awk -F '\t' -v hf="$HOSTFIELDS" -v ct="$CONTACT" '
    BEGIN {
      while ((getline l < hf) > 0) {
        split(l, a, "\t")
        if (a[2] == "Last connected") { v = a[3]; sub(/[ \t].*/, "", v); lc[a[1]] = v }
        else if (a[2] == "Fleet read" && index(a[3], "key line present")) fr[a[1]] = 1
      }
      while ((getline l < ct) > 0) { split(l, a, "\t"); cl[a[1]] = a[2] }
    }
    { print $1 "\t" lc[$1] "\t" ($1 in fr ? 1 : 0) "\t" cl[$1] }
  ' "$HOSTS" >"$WORK/contact-join.tsv"
  us "$WORK/contact-join.tsv"
  : >"$WORK/late.tsv"
  while IFS="$US" read -r h lc fr cl; do
    [ -n "$h" ] || continue
    # An unparsable Last connected: is a gap, never a date to compare.
    epoch_of "$lc" >/dev/null || lc=
    last=$(date_max "$lc" "$cl")
    limit=90 cad="every 90 days"
    [ "$fr" = 1 ] && limit=2 cad="nightly, fleet read"
    if age=$(days_since "$last"); then
      [ "$age" -gt "$limit" ] || continue
      # The date, never "N days ago": that would change the page every
      # day, and two machines' commits of it would conflict.
      printf '%s\t%s\t%s — last contact %s; %s\n' \
        "$age" "$h" "$h" "$last" "$cad" >>"$WORK/late.tsv"
    else
      printf '%s\t%s\t%s — no contact on record; %s\n' \
        99999 "$h" "$h" "$cad" >>"$WORK/late.tsv"
    fi
  done <"$WORK/contact-join.tsv.us"
  if [ -s "$WORK/late.tsv" ]; then
    LC_ALL=C sort -t '	' -k1,1nr -k2,2 "$WORK/late.tsv" | while IFS='	' read -r _ h txt; do
      printf -- '- [%s](machines/%s/memory.md)%s\n' "$h" "$h" "${txt#"$h"}"
    done
  else
    echo "- Every host was reached within its cadence."
  fi
  echo
  echo "Generated by Hostwarden $HWVERSION."
} >"$WORK/overview.md"

# A memory/README.md a person wrote is theirs: it is left as it is,
# and said so, rather than overwritten by this page.
if [ -f "$OVERVIEW" ] && [ "$(head -n 1 "$OVERVIEW")" != "$OV_MARK" ]; then
  echo "hostwarden-map: $OVERVIEW was written by hand; the overview was not written" >&2
else
  cp "$WORK/overview.md" "$OVERVIEW" || die "cannot write $OVERVIEW"
fi
